server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
     prefix: classpath:/templates/
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
  devtools:
    restart:
      enabled: true    

mybatis:
  type-aliases-package: com.dragonball.model.**.entity
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
